<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="stylesheets/stylesheet.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="stylesheets/pygment_trac.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="stylesheets/print.css" media="print" />

    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <title>Interaktive Experimente</title>
  </head>

  <body>
    <header>
      <div class="inner">
        <h1>Interaktive Experimente</h1>
        <a href="https://github.com/mgje/Interaktive_Experimente" class="button"><small>View project on</small>GitHub</a>
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix">
        <section id="main-content">


<p>Auf dieser Seite finden Sie frei zugängliche interaktive Experimente</p>


- [Cäsar Verschlüsselung](http://mgje.github.io/Crypto/exp1/)
- [ROT-X Verschlüsselung](http://mgje.github.io/Crypto/exp3/index.html)
- [Monoalphabetische Verschlüsselung](http://mgje.github.io/Crypto/exp4/index.html)
- [Kryptoanalyse](http://mgje.github.io/Crypto/exp6/index.html)
- [Verschlüsselte Texte dechiffrieren](http://mgje.github.io/Crypto/exp7/index.html)
- [Huffman Codierung](http://mgje.github.io/Codierung/Huffman.html)
- [Lempel-Ziv-Welch (LZW) Codierung](http://mgje.github.io/Codierung/LZW_Mittel.html)
- [Lauflängen Codierung](http://mgje.github.io/Codierung/Lauflaengen_Mini.html)


## Internationaler Wettbewerb «Informatik-Biber»

Der internationale Wettbewerb «Informatik-Biber» richtet sich an Schülerinnen und Schüler der Grundstufe (dritte bis zwölfte Klasse). Jeweils im November können ganze Schulklassen online während einer Lektion teilnehmen. Im Jahr 2013 wurden fast 10'000 Teilnehmende registriert. Der schweizerische Verein für Informatik in der Ausbildung (SVIA) organisiert die Durchführung des Wettbewerbs in der Schweiz. 
[http://informatik-biber.ch](http://informatik-biber.ch)





<a name="designer-templates" class="anchor" href="#designer-templates"><span class="octicon octicon-link"></span></a>Designer Templates</h3>

<p>We've crafted some handsome templates for you to use. Go ahead and continue to layouts to browse through them. You can easily go back to edit your page before publishing. After publishing your page, you can revisit the page generator and switch to another theme. Your Page content will be preserved if it remained markdown format.</p>

<h3>
<a name="rather-drive-stick" class="anchor" href="#rather-drive-stick"><span class="octicon octicon-link"></span></a>Rather Drive Stick?</h3>

<p>If you prefer to not use the automatic generator, push a branch named <code>gh-pages</code> to your repository to create a page manually. In addition to supporting regular HTML content, GitHub Pages support Jekyll, a simple, blog aware static site generator written by our own Tom Preston-Werner. Jekyll makes it easy to create site-wide headers and footers without having to copy them across every page. It also offers intelligent blog support and other advanced templating features.</p>

<h3>
<a name="authors-and-contributors" class="anchor" href="#authors-and-contributors"><span class="octicon octicon-link"></span></a>Authors and Contributors</h3>

<p>You can <a href="https://github.com/blog/821" class="user-mention">@mention</a> a GitHub username to generate a link to their profile. The resulting <code>&lt;a&gt;</code> element will link to the contributor's GitHub Profile. For example: In 2007, Chris Wanstrath (<a href="https://github.com/defunkt" class="user-mention">@defunkt</a>), PJ Hyett (<a href="https://github.com/pjhyett" class="user-mention">@pjhyett</a>), and Tom Preston-Werner (<a href="https://github.com/mojombo" class="user-mention">@mojombo</a>) founded GitHub.</p>



        </section>

        <aside id="sidebar">
          <a href="https://github.com/mgje/Interaktive_Experimente/zipball/master" class="button">
            <small>Download</small>
            .zip file
          </a>
          <a href="https://github.com/mgje/Interaktive_Experimente/tarball/master" class="button">
            <small>Download</small>
            .tar.gz file
          </a>

          <p class="repo-owner"><a href="https://github.com/mgje/Interaktive_Experimente"></a> is maintained by <a href="https://github.com/mgje">mgje</a>.</p>

          <p>This page was generated by <a href="https://pages.github.com">GitHub Pages</a> using the Architect theme by <a href="https://twitter.com/jasonlong">Jason Long</a>.</p>
        </aside>
      </div>
    </div>

            <h3>
<a name="welcome-to-github-pages" class="anchor" href="#welcome-to-github-pages"><span class="octicon octicon-link"></span></a>Welcome to GitHub Pages.</h3>
  </body>
</html>